### ISSUE TITLE
Encountered the following questions, how do you solve the problem

### ISSUE THREAD

**Issue by Yangsheng93** [digiapulssi/docker-monitoring-zabbix-agent#6]
[root@localhost ~]# zabbix_get -s 192.168.58.128 -k docker.containers[3960a2551658,memory]
Traceback (most recent call last):
  File "/etc/zabbix/scripts/docker/discover.py", line 256, in <module>
    memory(args)
  File "/etc/zabbix/scripts/docker/discover.py", line 213, in memory
    memory_usage_last = single_stat_update(args, container_dir, "memory.usage_in_bytes")
  File "/etc/zabbix/scripts/docker/discover.py", line 163, in single_stat_update
    os.mkdir(args.container)
OSError: [Errno 13] Permission denied: '3960a2551658'

Error as shown above, I have tried to add zabbix to sudo, but have been prompted for the error, trouble you helping me

**Comment by dimuskin** [comment]
Can you provide more details? How do you run the container? what changes did you make with it after launch? As can be seen from the error, the program can not create (no permissions) the collection directory where the statistics will be temporarily stored.

PS I am not the developer of this program, but I actively use it without problems

**Comment by Yangsheng93** [comment]
I did not do anything on my docker is running through the root user.And zabbix added to the root group and docker group, from the error analysis, I would like to be underridden, your Python is 2 or 3?

**Comment by dimuskin** [comment]
most likely the problem is not in the version of the program, try to change the owner of the directory /etc/zabbix/scripts/docker/ to zabbix, like : `sudo chown zabbix /etc/zabbix/scripts/docker/`

**Comment by Yangsheng93** [comment]
Thank you, have been able to work properly.
